//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.21 at 08:53:48 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.omg.org/spec/DD/20100524/DC")
package com.zifang.util.bpmn.xml;
